-- MySQL Script generated by MySQL Workbench
-- 03/27/16 09:12:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Pinjemin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pinjemin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pinjemin` DEFAULT CHARACTER SET utf8 ;
USE `Pinjemin` ;

-- -----------------------------------------------------
-- Table `Pinjemin`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pinjemin`.`USER` (
  `UID` INT NOT NULL AUTO_INCREMENT,
  `AccountName` VARCHAR(60) NOT NULL,
  `RealName` VARCHAR(80) NOT NULL,
  `Bio` VARCHAR(240) NULL,
  `Fakultas` VARCHAR(60) NULL,
  `Prodi` VARCHAR(60) NULL,
  `Telepon` VARCHAR(15) NULL,
  `TotalRating` INT NOT NULL,
  `NumRating` INT NOT NULL,
  PRIMARY KEY (`UID`),
  UNIQUE INDEX `AccountName_UNIQUE` (`AccountName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pinjemin`.`ADDS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pinjemin`.`ADDS` (
  `UIAdder` INT NOT NULL,
  `UIAdded` INT NOT NULL,
  PRIMARY KEY (`UIAdded`, `UIAdder`),
  INDEX `UIDAdder_idx` (`UIAdder` ASC),
  CONSTRAINT `fk_UIDAdder`
    FOREIGN KEY (`UIAdder`)
    REFERENCES `Pinjemin`.`USER` (`UID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_UIDAdded`
    FOREIGN KEY (`UIAdded`)
    REFERENCES `Pinjemin`.`USER` (`UID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pinjemin`.`FRIEND`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pinjemin`.`FRIEND` (
  `UID1` INT NOT NULL,
  `UID2` INT NOT NULL,
  PRIMARY KEY (`UID1`, `UID2`),
  INDEX `UID2_idx` (`UID2` ASC),
  CONSTRAINT `fk_UID1`
    FOREIGN KEY (`UID1`)
    REFERENCES `Pinjemin`.`USER` (`UID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_UID2`
    FOREIGN KEY (`UID2`)
    REFERENCES `Pinjemin`.`USER` (`UID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pinjemin`.`POST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pinjemin`.`POST` (
  `PID` INT NOT NULL AUTO_INCREMENT,
  `UID` INT NULL,
  `Timestamp` TIMESTAMP NULL,
  `Deskripsi` VARCHAR(240) NULL,
  `NamaBarang` VARCHAR(60) NULL,
  PRIMARY KEY (`PID`),
  INDEX `UID_idx` (`UID` ASC),
  CONSTRAINT `fk_UID_POST`
    FOREIGN KEY (`UID`)
    REFERENCES `Pinjemin`.`USER` (`UID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pinjemin`.`KOMENTAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pinjemin`.`KOMENTAR` (
  `CID` INT NOT NULL AUTO_INCREMENT,
  `PID` INT NULL,
  `UID` INT NULL,
  `Timestamp` TIMESTAMP NULL,
  `Content` VARCHAR(240) NULL,
  PRIMARY KEY (`CID`),
  INDEX `UID_idx` (`UID` ASC),
  INDEX `PID_idx` (`PID` ASC),
  CONSTRAINT `fk_UID_KOMENTAR`
    FOREIGN KEY (`UID`)
    REFERENCES `Pinjemin`.`USER` (`UID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PID_KOMENTAR`
    FOREIGN KEY (`PID`)
    REFERENCES `Pinjemin`.`POST` (`PID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pinjemin`.`PENAWARAN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pinjemin`.`PENAWARAN` (
  `PID` INT NOT NULL,
  `Harga` INT NULL,
  PRIMARY KEY (`PID`),
  CONSTRAINT `fk_PID_PENAWARAN`
    FOREIGN KEY (`PID`)
    REFERENCES `Pinjemin`.`POST` (`PID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pinjemin`.`PERMINTAAN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pinjemin`.`PERMINTAAN` (
  `PID` INT NOT NULL,
  `LastNeed` DATETIME NULL,
  PRIMARY KEY (`PID`),
  CONSTRAINT `fk_PID_PERMINTAAN`
    FOREIGN KEY (`PID`)
    REFERENCES `Pinjemin`.`POST` (`PID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pinjemin`.`PEMINJAMAN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pinjemin`.`PEMINJAMAN` (
  `PID` INT NOT NULL,
  `PartnerUID` INT NULL,
  `TimestampMulai` TIMESTAMP NULL,
  `TimestampKembali` TIMESTAMP NULL,
  `Rating` INT(1) NULL,
  `Review` VARCHAR(240) NULL,
  `Status` VARCHAR(60) NULL,
  PRIMARY KEY (`PID`),
  CONSTRAINT `fk_PID_PEMINJAMAN`
    FOREIGN KEY (`PID`)
    REFERENCES `Pinjemin`.`POST` (`PID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PartnerUID_PEMINJAMAN`
    FOREIGN KEY (`PartnerUID`)
    REFERENCES `Pinjemin`.`USER` (`UID`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
