-- mysql script generated by mysql workbench
-- 03/27/16 09:12:14
-- model: new model    version: 1.0
-- mysql workbench forward engineering

set @old_unique_checks=@@unique_checks, unique_checks=0;
set @old_foreign_key_checks=@@foreign_key_checks, foreign_key_checks=0;
set @old_sql_mode=@@sql_mode, sql_mode='traditional,allow_invalid_dates';

create schema if not exists pinjemin;
use pinjemin;

-- -----------------------------------------------------
-- table `user`
-- -----------------------------------------------------
create table if not exists `user` (
  `UID` int not null auto_increment,
  `AccountName` varchar(60) not null,
  `RealName` varchar(80) not null,
  `Password` varchar(32) not null,
  `Bio` varchar(240) null,
  `Fakultas` varchar(60) null,
  `Prodi` varchar(60) null,
  `Telepon` varchar(15) null,
  `TotalRating` int not null default 0,
  `NumRating` int not null default 0,
  primary key (`uid`),
  unique index `accountname_unique` (`accountname` asc))
engine = innodb;


-- -----------------------------------------------------
-- table `adds`
-- -----------------------------------------------------
create table if not exists `adds` (
  `UIDAdder` int not null,
  `UIDAdded` int not null,
  primary key (`uidadded`, `uidadder`),
  index `uidadder_idx` (`uidadder` asc),
  constraint `fk_uidadder`
    foreign key (`uidadder`)
    references `user` (`uid`)
    on delete cascade
    on update cascade,
  constraint `fk_uidadded`
    foreign key (`uidadded`)
    references `user` (`uid`)
    on delete cascade
    on update cascade)
engine = innodb;


-- -----------------------------------------------------
-- table `friend`
-- -----------------------------------------------------
create table if not exists `friend` (
  `UID1` int not null,
  `UID2` int not null,
  primary key (`uid1`, `uid2`),
  index `uid2_idx` (`uid2` asc),
  constraint `fk_uid1`
    foreign key (`uid1`)
    references `user` (`uid`)
    on delete cascade
    on update cascade,
  constraint `fk_uid2`
    foreign key (`uid2`)
    references `user` (`uid`)
    on delete cascade
    on update cascade)
engine = innodb;


-- -----------------------------------------------------
-- table `post`
-- -----------------------------------------------------
create table if not exists `post` (
  `PID` int not null auto_increment,
  `UID` int not null,
  `Timestamp` timestamp null default current_timestamp,
  `NamaBarang` varchar(60) null,
  `Deskripsi` varchar(240) null,
  primary key (`pid`),
  index `uid_idx` (`uid` asc),
  constraint `fk_uid_post`
    foreign key (`uid`)
    references `user` (`uid`)
    on delete cascade
    on update cascade)
engine = innodb;


-- -----------------------------------------------------
-- table `komentar`
-- -----------------------------------------------------
create table if not exists `komentar` (
  `CID` int not null auto_increment,
  `PID` int not null,
  `UID` int null,
  `Timestamp` timestamp null default current_timestamp,
  `Content` varchar(240) null,
  `ParentUID` int not null,
  primary key (`cid`),
  index `uid_idx` (`uid` asc),
  index `pid_idx` (`pid` asc),
  constraint `fk_uid_komentar`
    foreign key (`uid`)
    references `user` (`uid`)
    on delete cascade
    on update cascade,
  constraint `fk_parentuid_komentar`
    foreign key (`parentuid`)
    references `user` (`uid`)
    on delete cascade
    on update cascade,
  constraint `fk_pid_komentar`
    foreign key (`pid`)
    references `post` (`pid`)
    on delete cascade
    on update cascade)
engine = innodb;


-- -----------------------------------------------------
-- table `penawaran`
-- -----------------------------------------------------
create table if not exists `penawaran` (
  `PID` int not null,
  `Harga` int null default 0,
  primary key (`pid`),
  constraint `fk_pid_penawaran`
    foreign key (`pid`)
    references `post` (`pid`)
    on delete cascade
    on update cascade)
engine = innodb;


-- -----------------------------------------------------
-- table `permintaan`
-- -----------------------------------------------------
create table if not exists `permintaan` (
  `PID` int not null,
  `LastNeed` datetime null,
  primary key (`pid`),
  constraint `fk_pid_permintaan`
    foreign key (`pid`)
    references `post` (`pid`)
    on delete cascade
    on update cascade)
engine = innodb;


-- -----------------------------------------------------
-- table `peminjaman`
-- -----------------------------------------------------
create table if not exists `peminjaman` (
  `PID` int not null,
  `UIDPemberi` int not null,
  `UIDPenerima` int not null,
  `Deadline` datetime not null,
  `TimestampMulai` timestamp null,
  `TimestampKembali` timestamp null,
  `Rating` int(1) null,
  `Review` varchar(240) null,
  `Status` varchar(60) null,
  primary key (`pid`),
  constraint `fk_pid_peminjaman`
    foreign key (`pid`)
    references `post` (`pid`)
    on delete cascade
    on update cascade,
  constraint `fk_uidpemberi_peminjaman`
    foreign key (`UIDPemberi`)
    references `user` (`uid`)
    on delete cascade
    on update cascade,
  constraint `fk_uidpenerima_peminjaman`
    foreign key (`UIDPenerima`)
    references `user` (`uid`)
    on delete cascade
    on update cascade)
engine = innodb;


-- -----------------------------------------------------
-- table `konfirmasi`
-- -----------------------------------------------------
create table if not exists `konfirmasi` (
  `PID` int not null,
  `UID` int not null,
  `Deadline` datetime not null,
  primary key (`pid`, `uid`),
  constraint `fk_pid_konfirmasi`
    foreign key (`pid`)
    references `post` (`pid`)
    on delete cascade
    on update cascade,
  constraint `fk_uid_konfirmasi`
    foreign key (`uid`)
    references `user` (`uid`)
    on delete cascade
    on update cascade)
engine = innodb;

-- -----------------------------------------------------
-- table `lastseen`
-- -----------------------------------------------------
create table if not exists `lastseen` (
  `UID` int not null,
  `PID` int not null,
  `LastSeen` datetime not null,
  primary key (`uid`, `pid`),
  constraint `fk_pid_lastseen`
    foreign key (`pid`)
    references `post` (`pid`)
    on delete cascade
    on update cascade,
  constraint `fk_uid_lastseen`
    foreign key (`uid`)
    references `user` (`uid`)
    on delete cascade
    on update cascade)
engine = innodb;

set sql_mode=@old_sql_mode;
set foreign_key_checks=@old_foreign_key_checks;
set unique_checks=@old_unique_checks;
